// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Time
{
    /// <summary>
    /// ## Example Usage
    /// ### Basic Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Time = Pulumiverse.Time;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var example = new Time.Offset("example", new Time.OffsetArgs
    ///         {
    ///             OffsetDays = 7,
    ///         });
    ///         this.OneWeekFromNow = example.Rfc3339;
    ///     }
    /// 
    ///     [Output("oneWeekFromNow")]
    ///     public Output&lt;string&gt; OneWeekFromNow { get; set; }
    /// }
    /// ```
    /// ### Triggers Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Aws = Pulumi.Aws;
    /// using Time = Pulumiverse.Time;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var amiUpdate = new Time.Offset("amiUpdate", new Time.OffsetArgs
    ///         {
    ///             Triggers = 
    ///             {
    ///                 { "ami_id", data.Aws_ami.Example.Id },
    ///             },
    ///             OffsetDays = 7,
    ///         });
    ///         var server = new Aws.Ec2.Instance("server", new Aws.Ec2.InstanceArgs
    ///         {
    ///             Ami = amiUpdate.Triggers.Apply(triggers =&gt; triggers?.AmiId),
    ///             Tags = 
    ///             {
    ///                 { "ExpirationTime", amiUpdate.Rfc3339 },
    ///             },
    ///         });
    ///         // ... (other aws_instance arguments) ...
    ///     }
    /// 
    /// }
    /// ```
    /// 
    /// ## Import
    /// 
    /// This resource can be imported using the base UTC RFC3339 timestamp and offset years, months, days, hours, minutes, and seconds, separated by commas (`,`), e.g.
    /// 
    /// ```sh
    ///  $ pulumi import time:index/offset:Offset example 2020-02-12T06:36:13Z,0,0,7,0,0,0
    /// ```
    /// 
    ///  The `triggers` argument cannot be imported.
    /// </summary>
    [TimeResourceType("time:index/offset:Offset")]
    public partial class Offset : Pulumi.CustomResource
    {
        /// <summary>
        /// Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
        /// string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
        /// </summary>
        [Output("baseRfc3339")]
        public Output<string> BaseRfc3339 { get; private set; } = null!;

        /// <summary>
        /// Number day of offset timestamp.
        /// </summary>
        [Output("day")]
        public Output<int> Day { get; private set; } = null!;

        /// <summary>
        /// Number hour of offset timestamp.
        /// </summary>
        [Output("hour")]
        public Output<int> Hour { get; private set; } = null!;

        /// <summary>
        /// Number minute of offset timestamp.
        /// </summary>
        [Output("minute")]
        public Output<int> Minute { get; private set; } = null!;

        /// <summary>
        /// Number month of offset timestamp.
        /// </summary>
        [Output("month")]
        public Output<int> Month { get; private set; } = null!;

        /// <summary>
        /// Number of days to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Output("offsetDays")]
        public Output<int?> OffsetDays { get; private set; } = null!;

        /// <summary>
        /// Number of hours to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Output("offsetHours")]
        public Output<int?> OffsetHours { get; private set; } = null!;

        /// <summary>
        /// Number of minutes to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Output("offsetMinutes")]
        public Output<int?> OffsetMinutes { get; private set; } = null!;

        /// <summary>
        /// Number of months to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Output("offsetMonths")]
        public Output<int?> OffsetMonths { get; private set; } = null!;

        /// <summary>
        /// Number of seconds to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Output("offsetSeconds")]
        public Output<int?> OffsetSeconds { get; private set; } = null!;

        /// <summary>
        /// Number of years to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Output("offsetYears")]
        public Output<int?> OffsetYears { get; private set; } = null!;

        /// <summary>
        /// RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
        /// </summary>
        [Output("rfc3339")]
        public Output<string> Rfc3339 { get; private set; } = null!;

        /// <summary>
        /// Number second of offset timestamp.
        /// </summary>
        [Output("second")]
        public Output<int> Second { get; private set; } = null!;

        /// <summary>
        /// Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
        /// documentation](../index.md) for more information.
        /// </summary>
        [Output("triggers")]
        public Output<ImmutableDictionary<string, string>?> Triggers { get; private set; } = null!;

        /// <summary>
        /// Number of seconds since epoch time, e.g. `1581489373`.
        /// </summary>
        [Output("unix")]
        public Output<int> Unix { get; private set; } = null!;

        /// <summary>
        /// Number year of offset timestamp.
        /// </summary>
        [Output("year")]
        public Output<int> Year { get; private set; } = null!;


        /// <summary>
        /// Create a Offset resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Offset(string name, OffsetArgs? args = null, CustomResourceOptions? options = null)
            : base("time:index/offset:Offset", name, args ?? new OffsetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Offset(string name, Input<string> id, OffsetState? state = null, CustomResourceOptions? options = null)
            : base("time:index/offset:Offset", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-time",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Offset resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Offset Get(string name, Input<string> id, OffsetState? state = null, CustomResourceOptions? options = null)
        {
            return new Offset(name, id, state, options);
        }
    }

    public sealed class OffsetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
        /// string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
        /// </summary>
        [Input("baseRfc3339")]
        public Input<string>? BaseRfc3339 { get; set; }

        /// <summary>
        /// Number of days to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetDays")]
        public Input<int>? OffsetDays { get; set; }

        /// <summary>
        /// Number of hours to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetHours")]
        public Input<int>? OffsetHours { get; set; }

        /// <summary>
        /// Number of minutes to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetMinutes")]
        public Input<int>? OffsetMinutes { get; set; }

        /// <summary>
        /// Number of months to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetMonths")]
        public Input<int>? OffsetMonths { get; set; }

        /// <summary>
        /// Number of seconds to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetSeconds")]
        public Input<int>? OffsetSeconds { get; set; }

        /// <summary>
        /// Number of years to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetYears")]
        public Input<int>? OffsetYears { get; set; }

        [Input("triggers")]
        private InputMap<string>? _triggers;

        /// <summary>
        /// Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
        /// documentation](../index.md) for more information.
        /// </summary>
        public InputMap<string> Triggers
        {
            get => _triggers ?? (_triggers = new InputMap<string>());
            set => _triggers = value;
        }

        public OffsetArgs()
        {
        }
    }

    public sealed class OffsetState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
        /// string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
        /// </summary>
        [Input("baseRfc3339")]
        public Input<string>? BaseRfc3339 { get; set; }

        /// <summary>
        /// Number day of offset timestamp.
        /// </summary>
        [Input("day")]
        public Input<int>? Day { get; set; }

        /// <summary>
        /// Number hour of offset timestamp.
        /// </summary>
        [Input("hour")]
        public Input<int>? Hour { get; set; }

        /// <summary>
        /// Number minute of offset timestamp.
        /// </summary>
        [Input("minute")]
        public Input<int>? Minute { get; set; }

        /// <summary>
        /// Number month of offset timestamp.
        /// </summary>
        [Input("month")]
        public Input<int>? Month { get; set; }

        /// <summary>
        /// Number of days to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetDays")]
        public Input<int>? OffsetDays { get; set; }

        /// <summary>
        /// Number of hours to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetHours")]
        public Input<int>? OffsetHours { get; set; }

        /// <summary>
        /// Number of minutes to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetMinutes")]
        public Input<int>? OffsetMinutes { get; set; }

        /// <summary>
        /// Number of months to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetMonths")]
        public Input<int>? OffsetMonths { get; set; }

        /// <summary>
        /// Number of seconds to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetSeconds")]
        public Input<int>? OffsetSeconds { get; set; }

        /// <summary>
        /// Number of years to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
        /// </summary>
        [Input("offsetYears")]
        public Input<int>? OffsetYears { get; set; }

        /// <summary>
        /// RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
        /// </summary>
        [Input("rfc3339")]
        public Input<string>? Rfc3339 { get; set; }

        /// <summary>
        /// Number second of offset timestamp.
        /// </summary>
        [Input("second")]
        public Input<int>? Second { get; set; }

        [Input("triggers")]
        private InputMap<string>? _triggers;

        /// <summary>
        /// Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
        /// documentation](../index.md) for more information.
        /// </summary>
        public InputMap<string> Triggers
        {
            get => _triggers ?? (_triggers = new InputMap<string>());
            set => _triggers = value;
        }

        /// <summary>
        /// Number of seconds since epoch time, e.g. `1581489373`.
        /// </summary>
        [Input("unix")]
        public Input<int>? Unix { get; set; }

        /// <summary>
        /// Number year of offset timestamp.
        /// </summary>
        [Input("year")]
        public Input<int>? Year { get; set; }

        public OffsetState()
        {
        }
    }
}
