// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Time
{
    /// <summary>
    /// ## Example Usage
    /// ### Triggers Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Aws = Pulumi.Aws;
    /// using Time = Pulumiverse.Time;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var exampleResourceAssociation = new Aws.Ram.ResourceAssociation("exampleResourceAssociation", new Aws.Ram.ResourceAssociationArgs
    ///         {
    ///             ResourceArn = aws_subnet.Example.Arn,
    ///             ResourceShareArn = aws_ram_resource_share.Example.Arn,
    ///         });
    ///         // AWS resources shared via Resource Access Manager can take a few seconds to
    ///         // propagate across AWS accounts after RAM returns a successful association.
    ///         var ramResourcePropagation = new Time.TimeSleep("ramResourcePropagation", new Time.TimeSleepArgs
    ///         {
    ///             CreateDuration = "60s",
    ///             Triggers = 
    ///             {
    ///                 { "subnet_arn", exampleResourceAssociation.ResourceArn },
    ///                 { "subnet_id", aws_subnet.Example.Id },
    ///             },
    ///         });
    ///         var exampleSubnetGroup = new Aws.Rds.SubnetGroup("exampleSubnetGroup", new Aws.Rds.SubnetGroupArgs
    ///         {
    ///             SubnetIds = 
    ///             {
    ///                 ramResourcePropagation.Triggers.Apply(triggers =&gt; triggers?.Subnet_id),
    ///             },
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// 
    /// ## Import
    /// 
    /// This resource can be imported with the `create_duration` and `destroy_duration`, separated by a comma (`,`). e.g. For 30 seconds create duration with no destroy durationconsole
    /// 
    /// ```sh
    ///  $ pulumi import time:index/timeSleep:TimeSleep example 30s,
    /// ```
    /// 
    ///  e.g. For 30 seconds destroy duration with no create durationconsole
    /// 
    /// ```sh
    ///  $ pulumi import time:index/timeSleep:TimeSleep example ,30s
    /// ```
    /// 
    ///  The `triggers` argument cannot be imported. [1]https://golang.org/pkg/time/#ParseDuration
    /// </summary>
    [TimeResourceType("time:index/timeSleep:TimeSleep")]
    public partial class TimeSleep : Pulumi.CustomResource
    {
        /// <summary>
        /// [Time duration](https://golang.org/pkg/time/#ParseDuration) to delay resource creation. For example, `30s` for 30 seconds or `5m` for 5 minutes. Updating this value by itself will not trigger a delay.
        /// </summary>
        [Output("createDuration")]
        public Output<string?> CreateDuration { get; private set; } = null!;

        [Output("destroyDuration")]
        public Output<string?> DestroyDuration { get; private set; } = null!;

        /// <summary>
        /// Arbitrary map of values that, when changed, will run any creation or destroy delays again. See the main provider documentation for more information.
        /// </summary>
        [Output("triggers")]
        public Output<ImmutableDictionary<string, string>?> Triggers { get; private set; } = null!;


        /// <summary>
        /// Create a TimeSleep resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TimeSleep(string name, TimeSleepArgs? args = null, CustomResourceOptions? options = null)
            : base("time:index/timeSleep:TimeSleep", name, args ?? new TimeSleepArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TimeSleep(string name, Input<string> id, TimeSleepState? state = null, CustomResourceOptions? options = null)
            : base("time:index/timeSleep:TimeSleep", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TimeSleep resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TimeSleep Get(string name, Input<string> id, TimeSleepState? state = null, CustomResourceOptions? options = null)
        {
            return new TimeSleep(name, id, state, options);
        }
    }

    public sealed class TimeSleepArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// [Time duration](https://golang.org/pkg/time/#ParseDuration) to delay resource creation. For example, `30s` for 30 seconds or `5m` for 5 minutes. Updating this value by itself will not trigger a delay.
        /// </summary>
        [Input("createDuration")]
        public Input<string>? CreateDuration { get; set; }

        [Input("destroyDuration")]
        public Input<string>? DestroyDuration { get; set; }

        [Input("triggers")]
        private InputMap<string>? _triggers;

        /// <summary>
        /// Arbitrary map of values that, when changed, will run any creation or destroy delays again. See the main provider documentation for more information.
        /// </summary>
        public InputMap<string> Triggers
        {
            get => _triggers ?? (_triggers = new InputMap<string>());
            set => _triggers = value;
        }

        public TimeSleepArgs()
        {
        }
    }

    public sealed class TimeSleepState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// [Time duration](https://golang.org/pkg/time/#ParseDuration) to delay resource creation. For example, `30s` for 30 seconds or `5m` for 5 minutes. Updating this value by itself will not trigger a delay.
        /// </summary>
        [Input("createDuration")]
        public Input<string>? CreateDuration { get; set; }

        [Input("destroyDuration")]
        public Input<string>? DestroyDuration { get; set; }

        [Input("triggers")]
        private InputMap<string>? _triggers;

        /// <summary>
        /// Arbitrary map of values that, when changed, will run any creation or destroy delays again. See the main provider documentation for more information.
        /// </summary>
        public InputMap<string> Triggers
        {
            get => _triggers ?? (_triggers = new InputMap<string>());
            set => _triggers = value;
        }

        public TimeSleepState()
        {
        }
    }
}
