// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.time;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.time.StaticArgs;
import com.pulumiverse.time.Utilities;
import com.pulumiverse.time.inputs.StaticState;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * ### Basic Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.time.Static;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new Static(&#34;example&#34;);
 * 
 *         ctx.export(&#34;currentTime&#34;, example.rfc3339());
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### Triggers Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.time.Static;
 * import com.pulumi.time.StaticArgs;
 * import com.pulumi.aws.ec2.Instance;
 * import com.pulumi.aws.ec2.InstanceArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var amiUpdate = new Static(&#34;amiUpdate&#34;, StaticArgs.builder()
 *             .triggers(Map.of(&#34;ami_id&#34;, data.aws_ami().example().id()))
 *             .build());
 * 
 *         var server = new Instance(&#34;server&#34;, InstanceArgs.builder()
 *             .ami(amiUpdate.triggers().applyValue(triggers -&gt; triggers.amiId()))
 *             .tags(Map.of(&#34;AmiUpdateTime&#34;, amiUpdate.rfc3339()))
 *             .build());
 * 
 *         // ... (other aws_instance arguments) ...
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * This resource can be imported using the UTC RFC3339 value, e.g.
 * 
 * ```sh
 * $ pulumi import time:index/static:Static example 2020-02-12T06:36:13Z
 * ```
 * 
 * The `triggers` argument cannot be imported.
 * 
 */
@ResourceType(type="time:index/static:Static")
public class Static extends com.pulumi.resources.CustomResource {
    /**
     * Number day of timestamp.
     * 
     */
    @Export(name="day", refs={Integer.class}, tree="[0]")
    private Output<Integer> day;

    /**
     * @return Number day of timestamp.
     * 
     */
    public Output<Integer> day() {
        return this.day;
    }
    /**
     * Number hour of timestamp.
     * 
     */
    @Export(name="hour", refs={Integer.class}, tree="[0]")
    private Output<Integer> hour;

    /**
     * @return Number hour of timestamp.
     * 
     */
    public Output<Integer> hour() {
        return this.hour;
    }
    /**
     * Number minute of timestamp.
     * 
     */
    @Export(name="minute", refs={Integer.class}, tree="[0]")
    private Output<Integer> minute;

    /**
     * @return Number minute of timestamp.
     * 
     */
    public Output<Integer> minute() {
        return this.minute;
    }
    /**
     * Number month of timestamp.
     * 
     */
    @Export(name="month", refs={Integer.class}, tree="[0]")
    private Output<Integer> month;

    /**
     * @return Number month of timestamp.
     * 
     */
    public Output<Integer> month() {
        return this.month;
    }
    /**
     * Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     * 
     */
    @Export(name="rfc3339", refs={String.class}, tree="[0]")
    private Output<String> rfc3339;

    /**
     * @return Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     * 
     */
    public Output<String> rfc3339() {
        return this.rfc3339;
    }
    /**
     * Number second of timestamp.
     * 
     */
    @Export(name="second", refs={Integer.class}, tree="[0]")
    private Output<Integer> second;

    /**
     * @return Number second of timestamp.
     * 
     */
    public Output<Integer> second() {
        return this.second;
    }
    /**
     * Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See the main provider documentation for more information.
     * 
     */
    @Export(name="triggers", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> triggers;

    /**
     * @return Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See the main provider documentation for more information.
     * 
     */
    public Output<Optional<Map<String,String>>> triggers() {
        return Codegen.optional(this.triggers);
    }
    /**
     * Number of seconds since epoch time, e.g. `1581489373`.
     * 
     */
    @Export(name="unix", refs={Integer.class}, tree="[0]")
    private Output<Integer> unix;

    /**
     * @return Number of seconds since epoch time, e.g. `1581489373`.
     * 
     */
    public Output<Integer> unix() {
        return this.unix;
    }
    /**
     * Number year of timestamp.
     * 
     */
    @Export(name="year", refs={Integer.class}, tree="[0]")
    private Output<Integer> year;

    /**
     * @return Number year of timestamp.
     * 
     */
    public Output<Integer> year() {
        return this.year;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Static(String name) {
        this(name, StaticArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Static(String name, @Nullable StaticArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Static(String name, @Nullable StaticArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("time:index/static:Static", name, args == null ? StaticArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Static(String name, Output<String> id, @Nullable StaticState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("time:index/static:Static", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Static get(String name, Output<String> id, @Nullable StaticState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Static(name, id, state, options);
    }
}
