// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.time;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.time.TimeSleepArgs;
import com.pulumiverse.time.Utilities;
import com.pulumiverse.time.inputs.TimeSleepState;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ### Triggers Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ram.ResourceAssociation;
 * import com.pulumi.aws.ram.ResourceAssociationArgs;
 * import com.pulumi.time.TimeSleep;
 * import com.pulumi.time.TimeSleepArgs;
 * import com.pulumi.aws.rds.SubnetGroup;
 * import com.pulumi.aws.rds.SubnetGroupArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var exampleResourceAssociation = new ResourceAssociation(&#34;exampleResourceAssociation&#34;, ResourceAssociationArgs.builder()        
 *             .resourceArn(aws_subnet.example().arn())
 *             .resourceShareArn(aws_ram_resource_share.example().arn())
 *             .build());
 * 
 *         var ramResourcePropagation = new TimeSleep(&#34;ramResourcePropagation&#34;, TimeSleepArgs.builder()        
 *             .createDuration(&#34;60s&#34;)
 *             .triggers(Map.ofEntries(
 *                 Map.entry(&#34;subnet_arn&#34;, exampleResourceAssociation.resourceArn()),
 *                 Map.entry(&#34;subnet_id&#34;, aws_subnet.example().id())
 *             ))
 *             .build());
 * 
 *         var exampleSubnetGroup = new SubnetGroup(&#34;exampleSubnetGroup&#34;, SubnetGroupArgs.builder()        
 *             .subnetIds(ramResourcePropagation.triggers().applyValue(triggers -&gt; triggers.subnet_id()))
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * This resource can be imported with the `create_duration` and `destroy_duration`, separated by a comma (`,`). e.g. For 30 seconds create duration with no destroy durationconsole
 * 
 * ```sh
 *  $ pulumi import time:index/timeSleep:TimeSleep example 30s,
 * ```
 * 
 *  e.g. For 30 seconds destroy duration with no create durationconsole
 * 
 * ```sh
 *  $ pulumi import time:index/timeSleep:TimeSleep example ,30s
 * ```
 * 
 *  The `triggers` argument cannot be imported. [1]https://golang.org/pkg/time/#ParseDuration
 * 
 */
@ResourceType(type="time:index/timeSleep:TimeSleep")
public class TimeSleep extends com.pulumi.resources.CustomResource {
    /**
     * [Time duration](https://golang.org/pkg/time/#ParseDuration) to delay resource creation. For example, `30s` for 30 seconds or `5m` for 5 minutes. Updating this value by itself will not trigger a delay.
     * 
     */
    @Export(name="createDuration", type=String.class, parameters={})
    private Output</* @Nullable */ String> createDuration;

    /**
     * @return [Time duration](https://golang.org/pkg/time/#ParseDuration) to delay resource creation. For example, `30s` for 30 seconds or `5m` for 5 minutes. Updating this value by itself will not trigger a delay.
     * 
     */
    public Output<Optional<String>> createDuration() {
        return Codegen.optional(this.createDuration);
    }
    @Export(name="destroyDuration", type=String.class, parameters={})
    private Output</* @Nullable */ String> destroyDuration;

    public Output<Optional<String>> destroyDuration() {
        return Codegen.optional(this.destroyDuration);
    }
    /**
     * Arbitrary map of values that, when changed, will run any creation or destroy delays again. See the main provider documentation for more information.
     * 
     */
    @Export(name="triggers", type=Map.class, parameters={String.class, String.class})
    private Output</* @Nullable */ Map<String,String>> triggers;

    /**
     * @return Arbitrary map of values that, when changed, will run any creation or destroy delays again. See the main provider documentation for more information.
     * 
     */
    public Output<Optional<Map<String,String>>> triggers() {
        return Codegen.optional(this.triggers);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TimeSleep(String name) {
        this(name, TimeSleepArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TimeSleep(String name, @Nullable TimeSleepArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TimeSleep(String name, @Nullable TimeSleepArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("time:index/timeSleep:TimeSleep", name, args == null ? TimeSleepArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private TimeSleep(String name, Output<String> id, @Nullable TimeSleepState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("time:index/timeSleep:TimeSleep", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TimeSleep get(String name, Output<String> id, @Nullable TimeSleepState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TimeSleep(name, id, state, options);
    }
}
