// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.time.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OffsetState extends com.pulumi.resources.ResourceArgs {

    public static final OffsetState Empty = new OffsetState();

    /**
     * Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
     * string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     * 
     */
    @Import(name="baseRfc3339")
    private @Nullable Output<String> baseRfc3339;

    /**
     * @return Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
     * string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     * 
     */
    public Optional<Output<String>> baseRfc3339() {
        return Optional.ofNullable(this.baseRfc3339);
    }

    /**
     * Number day of offset timestamp.
     * 
     */
    @Import(name="day")
    private @Nullable Output<Integer> day;

    /**
     * @return Number day of offset timestamp.
     * 
     */
    public Optional<Output<Integer>> day() {
        return Optional.ofNullable(this.day);
    }

    /**
     * Number hour of offset timestamp.
     * 
     */
    @Import(name="hour")
    private @Nullable Output<Integer> hour;

    /**
     * @return Number hour of offset timestamp.
     * 
     */
    public Optional<Output<Integer>> hour() {
        return Optional.ofNullable(this.hour);
    }

    /**
     * Number minute of offset timestamp.
     * 
     */
    @Import(name="minute")
    private @Nullable Output<Integer> minute;

    /**
     * @return Number minute of offset timestamp.
     * 
     */
    public Optional<Output<Integer>> minute() {
        return Optional.ofNullable(this.minute);
    }

    /**
     * Number month of offset timestamp.
     * 
     */
    @Import(name="month")
    private @Nullable Output<Integer> month;

    /**
     * @return Number month of offset timestamp.
     * 
     */
    public Optional<Output<Integer>> month() {
        return Optional.ofNullable(this.month);
    }

    /**
     * Number of days to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    @Import(name="offsetDays")
    private @Nullable Output<Integer> offsetDays;

    /**
     * @return Number of days to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    public Optional<Output<Integer>> offsetDays() {
        return Optional.ofNullable(this.offsetDays);
    }

    /**
     * Number of hours to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    @Import(name="offsetHours")
    private @Nullable Output<Integer> offsetHours;

    /**
     * @return Number of hours to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    public Optional<Output<Integer>> offsetHours() {
        return Optional.ofNullable(this.offsetHours);
    }

    /**
     * Number of minutes to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    @Import(name="offsetMinutes")
    private @Nullable Output<Integer> offsetMinutes;

    /**
     * @return Number of minutes to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    public Optional<Output<Integer>> offsetMinutes() {
        return Optional.ofNullable(this.offsetMinutes);
    }

    /**
     * Number of months to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    @Import(name="offsetMonths")
    private @Nullable Output<Integer> offsetMonths;

    /**
     * @return Number of months to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    public Optional<Output<Integer>> offsetMonths() {
        return Optional.ofNullable(this.offsetMonths);
    }

    /**
     * Number of seconds to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    @Import(name="offsetSeconds")
    private @Nullable Output<Integer> offsetSeconds;

    /**
     * @return Number of seconds to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    public Optional<Output<Integer>> offsetSeconds() {
        return Optional.ofNullable(this.offsetSeconds);
    }

    /**
     * Number of years to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    @Import(name="offsetYears")
    private @Nullable Output<Integer> offsetYears;

    /**
     * @return Number of years to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
     * 
     */
    public Optional<Output<Integer>> offsetYears() {
        return Optional.ofNullable(this.offsetYears);
    }

    /**
     * RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
     * 
     */
    @Import(name="rfc3339")
    private @Nullable Output<String> rfc3339;

    /**
     * @return RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
     * 
     */
    public Optional<Output<String>> rfc3339() {
        return Optional.ofNullable(this.rfc3339);
    }

    /**
     * Number second of offset timestamp.
     * 
     */
    @Import(name="second")
    private @Nullable Output<Integer> second;

    /**
     * @return Number second of offset timestamp.
     * 
     */
    public Optional<Output<Integer>> second() {
        return Optional.ofNullable(this.second);
    }

    /**
     * Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
     * documentation](../index.md) for more information.
     * 
     */
    @Import(name="triggers")
    private @Nullable Output<Map<String,String>> triggers;

    /**
     * @return Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
     * documentation](../index.md) for more information.
     * 
     */
    public Optional<Output<Map<String,String>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    /**
     * Number of seconds since epoch time, e.g. `1581489373`.
     * 
     */
    @Import(name="unix")
    private @Nullable Output<Integer> unix;

    /**
     * @return Number of seconds since epoch time, e.g. `1581489373`.
     * 
     */
    public Optional<Output<Integer>> unix() {
        return Optional.ofNullable(this.unix);
    }

    /**
     * Number year of offset timestamp.
     * 
     */
    @Import(name="year")
    private @Nullable Output<Integer> year;

    /**
     * @return Number year of offset timestamp.
     * 
     */
    public Optional<Output<Integer>> year() {
        return Optional.ofNullable(this.year);
    }

    private OffsetState() {}

    private OffsetState(OffsetState $) {
        this.baseRfc3339 = $.baseRfc3339;
        this.day = $.day;
        this.hour = $.hour;
        this.minute = $.minute;
        this.month = $.month;
        this.offsetDays = $.offsetDays;
        this.offsetHours = $.offsetHours;
        this.offsetMinutes = $.offsetMinutes;
        this.offsetMonths = $.offsetMonths;
        this.offsetSeconds = $.offsetSeconds;
        this.offsetYears = $.offsetYears;
        this.rfc3339 = $.rfc3339;
        this.second = $.second;
        this.triggers = $.triggers;
        this.unix = $.unix;
        this.year = $.year;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OffsetState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OffsetState $;

        public Builder() {
            $ = new OffsetState();
        }

        public Builder(OffsetState defaults) {
            $ = new OffsetState(Objects.requireNonNull(defaults));
        }

        /**
         * @param baseRfc3339 Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
         * string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
         * 
         * @return builder
         * 
         */
        public Builder baseRfc3339(@Nullable Output<String> baseRfc3339) {
            $.baseRfc3339 = baseRfc3339;
            return this;
        }

        /**
         * @param baseRfc3339 Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time
         * string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
         * 
         * @return builder
         * 
         */
        public Builder baseRfc3339(String baseRfc3339) {
            return baseRfc3339(Output.of(baseRfc3339));
        }

        /**
         * @param day Number day of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder day(@Nullable Output<Integer> day) {
            $.day = day;
            return this;
        }

        /**
         * @param day Number day of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder day(Integer day) {
            return day(Output.of(day));
        }

        /**
         * @param hour Number hour of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder hour(@Nullable Output<Integer> hour) {
            $.hour = hour;
            return this;
        }

        /**
         * @param hour Number hour of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder hour(Integer hour) {
            return hour(Output.of(hour));
        }

        /**
         * @param minute Number minute of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder minute(@Nullable Output<Integer> minute) {
            $.minute = minute;
            return this;
        }

        /**
         * @param minute Number minute of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder minute(Integer minute) {
            return minute(Output.of(minute));
        }

        /**
         * @param month Number month of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder month(@Nullable Output<Integer> month) {
            $.month = month;
            return this;
        }

        /**
         * @param month Number month of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder month(Integer month) {
            return month(Output.of(month));
        }

        /**
         * @param offsetDays Number of days to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetDays(@Nullable Output<Integer> offsetDays) {
            $.offsetDays = offsetDays;
            return this;
        }

        /**
         * @param offsetDays Number of days to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetDays(Integer offsetDays) {
            return offsetDays(Output.of(offsetDays));
        }

        /**
         * @param offsetHours Number of hours to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetHours(@Nullable Output<Integer> offsetHours) {
            $.offsetHours = offsetHours;
            return this;
        }

        /**
         * @param offsetHours Number of hours to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetHours(Integer offsetHours) {
            return offsetHours(Output.of(offsetHours));
        }

        /**
         * @param offsetMinutes Number of minutes to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetMinutes(@Nullable Output<Integer> offsetMinutes) {
            $.offsetMinutes = offsetMinutes;
            return this;
        }

        /**
         * @param offsetMinutes Number of minutes to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetMinutes(Integer offsetMinutes) {
            return offsetMinutes(Output.of(offsetMinutes));
        }

        /**
         * @param offsetMonths Number of months to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetMonths(@Nullable Output<Integer> offsetMonths) {
            $.offsetMonths = offsetMonths;
            return this;
        }

        /**
         * @param offsetMonths Number of months to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetMonths(Integer offsetMonths) {
            return offsetMonths(Output.of(offsetMonths));
        }

        /**
         * @param offsetSeconds Number of seconds to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetSeconds(@Nullable Output<Integer> offsetSeconds) {
            $.offsetSeconds = offsetSeconds;
            return this;
        }

        /**
         * @param offsetSeconds Number of seconds to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetSeconds(Integer offsetSeconds) {
            return offsetSeconds(Output.of(offsetSeconds));
        }

        /**
         * @param offsetYears Number of years to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetYears(@Nullable Output<Integer> offsetYears) {
            $.offsetYears = offsetYears;
            return this;
        }

        /**
         * @param offsetYears Number of years to offset the base timestamp. At least one of the &#39;offset_&#39; arguments must be configured.
         * 
         * @return builder
         * 
         */
        public Builder offsetYears(Integer offsetYears) {
            return offsetYears(Output.of(offsetYears));
        }

        /**
         * @param rfc3339 RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
         * 
         * @return builder
         * 
         */
        public Builder rfc3339(@Nullable Output<String> rfc3339) {
            $.rfc3339 = rfc3339;
            return this;
        }

        /**
         * @param rfc3339 RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
         * 
         * @return builder
         * 
         */
        public Builder rfc3339(String rfc3339) {
            return rfc3339(Output.of(rfc3339));
        }

        /**
         * @param second Number second of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder second(@Nullable Output<Integer> second) {
            $.second = second;
            return this;
        }

        /**
         * @param second Number second of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder second(Integer second) {
            return second(Output.of(second));
        }

        /**
         * @param triggers Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
         * documentation](../index.md) for more information.
         * 
         * @return builder
         * 
         */
        public Builder triggers(@Nullable Output<Map<String,String>> triggers) {
            $.triggers = triggers;
            return this;
        }

        /**
         * @param triggers Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See [the main provider
         * documentation](../index.md) for more information.
         * 
         * @return builder
         * 
         */
        public Builder triggers(Map<String,String> triggers) {
            return triggers(Output.of(triggers));
        }

        /**
         * @param unix Number of seconds since epoch time, e.g. `1581489373`.
         * 
         * @return builder
         * 
         */
        public Builder unix(@Nullable Output<Integer> unix) {
            $.unix = unix;
            return this;
        }

        /**
         * @param unix Number of seconds since epoch time, e.g. `1581489373`.
         * 
         * @return builder
         * 
         */
        public Builder unix(Integer unix) {
            return unix(Output.of(unix));
        }

        /**
         * @param year Number year of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder year(@Nullable Output<Integer> year) {
            $.year = year;
            return this;
        }

        /**
         * @param year Number year of offset timestamp.
         * 
         * @return builder
         * 
         */
        public Builder year(Integer year) {
            return year(Output.of(year));
        }

        public OffsetState build() {
            return $;
        }
    }

}
