// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 * ### Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as time from "@pulumiverse/time";
 *
 * const example = new time.Offset("example", {offsetDays: 7});
 * export const oneWeekFromNow = example.rfc3339;
 * ```
 * ### Triggers Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as time from "@pulumiverse/time";
 *
 * const amiUpdate = new time.Offset("amiUpdate", {
 *     triggers: {
 *         ami_id: data.aws_ami.example.id,
 *     },
 *     offsetDays: 7,
 * });
 * const server = new aws.ec2.Instance("server", {
 *     ami: amiUpdate.triggers.apply(triggers => triggers?.amiId),
 *     tags: {
 *         ExpirationTime: amiUpdate.rfc3339,
 *     },
 * });
 * // ... (other aws_instance arguments) ...
 * ```
 *
 * ## Import
 *
 * This resource can be imported using the base UTC RFC3339 timestamp and offset years, months, days, hours, minutes, and seconds, separated by commas (`,`), e.g.
 *
 * ```sh
 *  $ pulumi import time:index/offset:Offset example 2020-02-12T06:36:13Z,0,0,7,0,0,0
 * ```
 *
 *  The `triggers` argument cannot be imported.
 */
export class Offset extends pulumi.CustomResource {
    /**
     * Get an existing Offset resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OffsetState, opts?: pulumi.CustomResourceOptions): Offset {
        return new Offset(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'time:index/offset:Offset';

    /**
     * Returns true if the given object is an instance of Offset.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Offset {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Offset.__pulumiType;
    }

    /**
     * Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     */
    public readonly baseRfc3339!: pulumi.Output<string>;
    /**
     * Number day of offset timestamp.
     */
    public /*out*/ readonly day!: pulumi.Output<number>;
    /**
     * Number hour of offset timestamp.
     */
    public /*out*/ readonly hour!: pulumi.Output<number>;
    /**
     * Number minute of offset timestamp.
     */
    public /*out*/ readonly minute!: pulumi.Output<number>;
    /**
     * Number month of offset timestamp.
     */
    public /*out*/ readonly month!: pulumi.Output<number>;
    /**
     * Number of days to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    public readonly offsetDays!: pulumi.Output<number | undefined>;
    /**
     * Number of hours to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    public readonly offsetHours!: pulumi.Output<number | undefined>;
    /**
     * Number of minutes to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    public readonly offsetMinutes!: pulumi.Output<number | undefined>;
    /**
     * Number of months to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    public readonly offsetMonths!: pulumi.Output<number | undefined>;
    /**
     * Number of seconds to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    public readonly offsetSeconds!: pulumi.Output<number | undefined>;
    /**
     * Number of years to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    public readonly offsetYears!: pulumi.Output<number | undefined>;
    /**
     * RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
     */
    public /*out*/ readonly rfc3339!: pulumi.Output<string>;
    /**
     * Number second of offset timestamp.
     */
    public /*out*/ readonly second!: pulumi.Output<number>;
    /**
     * Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See the main provider documentation for more information.
     */
    public readonly triggers!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Number of seconds since epoch time, e.g. `1581489373`.
     */
    public /*out*/ readonly unix!: pulumi.Output<number>;
    /**
     * Number year of offset timestamp.
     */
    public /*out*/ readonly year!: pulumi.Output<number>;

    /**
     * Create a Offset resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OffsetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OffsetArgs | OffsetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OffsetState | undefined;
            resourceInputs["baseRfc3339"] = state ? state.baseRfc3339 : undefined;
            resourceInputs["day"] = state ? state.day : undefined;
            resourceInputs["hour"] = state ? state.hour : undefined;
            resourceInputs["minute"] = state ? state.minute : undefined;
            resourceInputs["month"] = state ? state.month : undefined;
            resourceInputs["offsetDays"] = state ? state.offsetDays : undefined;
            resourceInputs["offsetHours"] = state ? state.offsetHours : undefined;
            resourceInputs["offsetMinutes"] = state ? state.offsetMinutes : undefined;
            resourceInputs["offsetMonths"] = state ? state.offsetMonths : undefined;
            resourceInputs["offsetSeconds"] = state ? state.offsetSeconds : undefined;
            resourceInputs["offsetYears"] = state ? state.offsetYears : undefined;
            resourceInputs["rfc3339"] = state ? state.rfc3339 : undefined;
            resourceInputs["second"] = state ? state.second : undefined;
            resourceInputs["triggers"] = state ? state.triggers : undefined;
            resourceInputs["unix"] = state ? state.unix : undefined;
            resourceInputs["year"] = state ? state.year : undefined;
        } else {
            const args = argsOrState as OffsetArgs | undefined;
            resourceInputs["baseRfc3339"] = args ? args.baseRfc3339 : undefined;
            resourceInputs["offsetDays"] = args ? args.offsetDays : undefined;
            resourceInputs["offsetHours"] = args ? args.offsetHours : undefined;
            resourceInputs["offsetMinutes"] = args ? args.offsetMinutes : undefined;
            resourceInputs["offsetMonths"] = args ? args.offsetMonths : undefined;
            resourceInputs["offsetSeconds"] = args ? args.offsetSeconds : undefined;
            resourceInputs["offsetYears"] = args ? args.offsetYears : undefined;
            resourceInputs["triggers"] = args ? args.triggers : undefined;
            resourceInputs["day"] = undefined /*out*/;
            resourceInputs["hour"] = undefined /*out*/;
            resourceInputs["minute"] = undefined /*out*/;
            resourceInputs["month"] = undefined /*out*/;
            resourceInputs["rfc3339"] = undefined /*out*/;
            resourceInputs["second"] = undefined /*out*/;
            resourceInputs["unix"] = undefined /*out*/;
            resourceInputs["year"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Offset.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Offset resources.
 */
export interface OffsetState {
    /**
     * Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     */
    baseRfc3339?: pulumi.Input<string>;
    /**
     * Number day of offset timestamp.
     */
    day?: pulumi.Input<number>;
    /**
     * Number hour of offset timestamp.
     */
    hour?: pulumi.Input<number>;
    /**
     * Number minute of offset timestamp.
     */
    minute?: pulumi.Input<number>;
    /**
     * Number month of offset timestamp.
     */
    month?: pulumi.Input<number>;
    /**
     * Number of days to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetDays?: pulumi.Input<number>;
    /**
     * Number of hours to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetHours?: pulumi.Input<number>;
    /**
     * Number of minutes to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetMinutes?: pulumi.Input<number>;
    /**
     * Number of months to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetMonths?: pulumi.Input<number>;
    /**
     * Number of seconds to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetSeconds?: pulumi.Input<number>;
    /**
     * Number of years to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetYears?: pulumi.Input<number>;
    /**
     * RFC3339 format of the offset timestamp, e.g. `2020-02-12T06:36:13Z`.
     */
    rfc3339?: pulumi.Input<string>;
    /**
     * Number second of offset timestamp.
     */
    second?: pulumi.Input<number>;
    /**
     * Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See the main provider documentation for more information.
     */
    triggers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Number of seconds since epoch time, e.g. `1581489373`.
     */
    unix?: pulumi.Input<number>;
    /**
     * Number year of offset timestamp.
     */
    year?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Offset resource.
 */
export interface OffsetArgs {
    /**
     * Base timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) format (see [RFC3339 time string](https://tools.ietf.org/html/rfc3339#section-5.8) e.g., `YYYY-MM-DDTHH:MM:SSZ`). Defaults to the current time.
     */
    baseRfc3339?: pulumi.Input<string>;
    /**
     * Number of days to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetDays?: pulumi.Input<number>;
    /**
     * Number of hours to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetHours?: pulumi.Input<number>;
    /**
     * Number of minutes to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetMinutes?: pulumi.Input<number>;
    /**
     * Number of months to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetMonths?: pulumi.Input<number>;
    /**
     * Number of seconds to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetSeconds?: pulumi.Input<number>;
    /**
     * Number of years to offset the base timestamp. At least one of the 'offset_' arguments must be configured.
     */
    offsetYears?: pulumi.Input<number>;
    /**
     * Arbitrary map of values that, when changed, will trigger a new base timestamp value to be saved. See the main provider documentation for more information.
     */
    triggers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
